// host-react/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";
import { Router } from "./router";

import "./index.css";

const App = () => (
    <div className="container">
        <div>Name: host-react</div>
        <div>Framework: react</div>
        <div>Language: TypeScript</div>
        <div>CSS: Empty CSS</div>
        <Router />
    </div>
);
ReactDOM.render(<App />, document.getElementById("app"));

// remote-vue/src/App.vue
<script setup lang="ts">
import Counter from "./counter/Counter.vue";
</script>

<template>
    <div class="container">
        <div>Name: remote-vue</div>
        <div>Framework: vue3</div>
        <div>Language: TypeScript</div>
        <div>CSS: Empty CSS</div>

        <Counter />
    </div>
</template>
